version: "3.8"

services:

  api_orders:
    image: orders_api:dev
    container_name: api-orders
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8001
    env_file:
      - .env
    depends_on:
      - postgres

  queue_orders:
    image: orders_api:dev
    container_name: queue-orders
    command: 'python -u consumer.py'
    env_file:
      - .env
    depends_on:
      - api_orders

  redis_orders:
    image: redis:6.2.5-alpine
    container_name: redis-orders
    ports:
      - 6379:6379

  postgres:
    image: postgres:13.4
    container_name: postgres
    environment:
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "postgrespwd"
      POSTGRES_DB: "ordersdb"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
        - 5432:5432

  postgres_test:
    image: postgres:13.4
    container_name: postgres-test
    environment:
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "postgrespwd"
      POSTGRES_DB: "ordersdbtest"
    volumes:
      - postgres-data-teste:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: postgres-data
  postgres-data-teste:
    name: postgres-data-teste
  
networks:
    default:
        external:
            name: orders-network
